name: Starknet Foundry Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Run Starknet Foundry Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install asdf and tools
        uses: asdf-vm/actions/install@v4
        with:
          tool_versions: |
            scarb latest
            starknet-foundry latest

      - name: Verify installations
        run: |
          scarb --version
          snforge --version

      - name: Install dependencies
        run: scarb install

      - name: Build contract
        run: scarb build
        continue-on-error: false

      - name: Run Starknet Foundry tests
        id: test_run
        run: snforge test
        continue-on-error: true

      - name: Process test results
        if: always()
        run: |
          if [ "${{ steps.test_run.outcome }}" == "success" ]; then
            echo "✅ All tests passed!"
            echo "TEST_STATUS=passed" >> $GITHUB_ENV
          else
            echo "❌ Tests failed. See logs for details."
            echo "TEST_STATUS=failed" >> $GITHUB_ENV
          fi

      - name: Create test summary
        if: always()
        run: |
          echo "## Test Results" > test_summary.md
          if [ "$TEST_STATUS" == "passed" ]; then
            echo "✅ **All tests passed!**" >> test_summary.md
          else
            echo "❌ **Tests failed**" >> test_summary.md
            echo "" >> test_summary.md
            echo "### Failure Logs" >> test_summary.md
            echo '```' >> test_summary.md
            echo "${{ steps.test_run.outputs.stderr || 'No detailed error information available' }}" >> test_summary.md
            echo '```' >> test_summary.md

      - name: Upload test summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_summary.md
